service: serverless-authentication-test-token # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3

defaults:
  stage: dev
  region: eu-west-1

functions:
  testToken:
    handler: handler.test
    events:
      - http:
          path: test-token
          method: get
          cors: true
          authorizer:
            arn: authorizer-function-arn
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
