service: serverless-authentication # change this

provider:
  name: aws
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:Scan
      - dynamodb:Query
      - dynamodb:PutItem
      - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:*
    - Effect: Allow
      Action:
      - cognito-sync:*
      - cognito-identity:*
      Resource: arn:aws:cognito-identity:*:*:*
  runtime: nodejs4.3

# Functions

functions:
  signin:
    handler: handler.signin
    memorySize: 256
    timeout: 15
    events:
      - http:
          path: authentication/signin/{provider}
          method: get
          integration: lambda-proxy
          request:
            template:
              application/json: "{\"provider\":\"$input.params('provider')\",\"host\":\"$input.params().header.get('host')\",\"stage\":\"$context.stage\"}"
  callback:
    handler: handler.callback
    memorySize: 256
    timeout: 15
    events:
      - http:
          path: authentication/callback/{provider}
          method: get
          integration: lambda-proxy
          request:
            template:
              application/json: "{\"provider\":\"$input.params('provider')\",\"code\":\"$input.params('code')\",\"state\":\"$input.params('state')\",\"host\":\"$input.params().header.get('host')\",\"stage\":\"$context.stage\"}"
  refresh:
    handler: handler.refresh
    memorySize: 256
    timeout: 15
    events:
      - http:
          path: authentication/refresh/{refresh_token}
          method: get
          cors: true
          integration: lambda
          request:
            template:
              application/json: "{\"refresh_token\":\"$input.params('refresh_token')\",\"id\":\"$input.params('id')\",\"state\":\"$input.params('state')\",\"host\":\"$input.params().header.get('host')\",\"stage\":\"$context.stage\"}"
  authorize:
    handler: handler.authorize

resources:
  Resources:
    Dynamo:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: Token
          AttributeType: S
        - AttributeName: Type
          AttributeType: S
        KeySchema:
        - AttributeName: Token
          KeyType: HASH
        - AttributeName: Type
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.stage}-${self:service}-cache
# Overwrites default 200 responses with 302, @todo change to use proxy
    ApiGatewayMethodAuthenticationSigninProviderVarGet:
      Type: AWS::ApiGateway::Method
      Properties:
        Integration:
          IntegrationResponses:
            - StatusCode: 302
              ResponseParameters:
                method.response.header.Location: integration.response.body.url
        MethodResponses:
          - StatusCode: 302
            ResponseParameters:
              method.response.header.Location: true
    ApiGatewayMethodAuthenticationCallbackProviderVarGet:
      Type: AWS::ApiGateway::Method
      Properties:
        Integration:
          IntegrationResponses:
            - StatusCode: 302
              ResponseParameters:
                method.response.header.Location: integration.response.body.url
        MethodResponses:
          - StatusCode: 302
            ResponseParameters:
              method.response.header.Location: true
